services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    ports:
      - "8090:80"   # Bypass: http://IP:8090
    environment:
      - NTFY_BASE_URL=http://ntfy.project-reloaded.org
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ENABLE_UPDATES=false
    volumes:
      - /srv/agents/ntfy/cache:/var/cache/ntfy
    networks:
      - agents_net
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ntfy.rule=Host(`ntfy.project-reloaded.org`)"
      - "traefik.http.routers.ntfy.entrypoints=web"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"

networks:
  agents_net:
    external: true
  traefik_net:
    external: true
    name: traefik_net
